### ISSUE TITLE
论文细节相关问题

### ISSUE THREAD

**Issue by DragonistYJ** [whale-ynu/TAN#1]
作者您好，我是四川大学一名硕士研究生，最近在研读您发表的《Topology-Aware Neural Model for Highly Accurate QoS Prediction》一文，受益匪浅。
但对于文中一些细节问题还存在疑惑，想请教您一下。
1. 您在计算最短路径的时候，用的是AS之间的最短地理距离还是最短跳数？如果是最短地理距离，那您中间的AS的经纬度是如果确定的呢？
2. 您在Github上给的data_demo里面的文件里的AS号是来自于ws-dream dataset1还是经过您二次处理的？如果您经过二次处理，那处理方式是什么呢？
期待您的回复，万分感谢~

**Comment by haowuster** [comment]
数据是依据AS拓扑数据构成的网络中的最短跳数决定的；
数据中的AS号直接来源于ws-dream dataset1，我们在拓扑数据中做了二次处理，重新映射了ID，以便做嵌入表征。



***@***.***
 
发件人： DragonistYJ
发送时间： 2022-07-15 10:58
收件人： whale-ynu/TAN
抄送： Subscribed
主题： [whale-ynu/TAN]论文细节相关问题 (Issue #1)
作者您好，我是四川大学一名硕士研究生，最近在研读您发表的《Topology-Aware Neural Model for Highly Accurate QoS Prediction》一文，受益匪浅。
但对于文中一些细节问题还存在疑惑，想请教您一下。
您在计算最短路径的时候，用的是AS之间的最短地理距离还是最短跳数？如果是最短地理距离，那您中间的AS的经纬度是如果确定的呢？
您在Github上给的data_demo里面的文件里的AS号是来自于ws-dream dataset1还是经过您二次处理的？如果您经过二次处理，那处理方式是什么呢？
期待您的回复，万分感谢~

**Comment by DragonistYJ** [comment]
您好，我已经收到您的周报，周报收取截止时间为每周二下午八点，八点后将截止收取，请按时发送您的周报，谢谢！

**Comment by DragonistYJ** [comment]
感谢您的细心解答，谢谢
